import Header from "@/components/Header";
import "./globals.css";
import { Inter } from "next/font/google";
import ThemeCtx from "./ThemeCtx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "IMDb Clone",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeCtx>
          <Header />
          {children}
        </ThemeCtx>
      </body>
    </html>
  );
}
